# -*- coding: utf-8 -*-
"""ab_test_stats_test

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E5-rihY8kjpUUku3lKfYQK_x9-7CS5Bn
"""

from statsmodels.stats.proportion import proportions_ztest

# Replace these with your SQL results
control_conversions = 3717
control_total = 30411

treatment_conversions = 3619
treatment_total = 30348

# Perform two-proportion z-test
successes = [control_conversions, treatment_conversions]
nobs = [control_total, treatment_total]

z_stat, p_value = proportions_ztest(count=successes, nobs=nobs)

print(f"Z-statistic: {z_stat:.4f}")
print(f"P-value: {p_value:.4f}")

Z-statistic: 1.1255
P-value: 0.2604